name: CI/CD for Flutter app
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.1.0
        with:
          flutter-version: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Build Android APK
        run: flutter build apk --release
        if: matrix.os == 'ubuntu-latest'
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Build iOS IPA
        uses: xavierha/ios-build@v3
        with:
          project_directory: .
          configuration: Release
        if: matrix.os == 'macos-latest'
      - name: Upload to Google Play Store
        uses: r0adkll/upload-github-action@v2.1.0
        if: matrix.os == 'ubuntu-latest'
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GOOGLE_PLAY_STORE_TOKEN }}
          release_notes: release_notes.txt
          track: internal
      - name: Upload to App Store
        uses: MaxBittker/action-ios-app-store@v1
        if: matrix.os == 'macos-latest'
        with:
          app_id: ${{ secrets.APP_STORE_APP_ID }}
          username: ${{ secrets.APP_STORE_USERNAME }}
          password: ${{ secrets.APP_STORE_PASSWORD }}
          ipa_path: Runner.ipa
      - name: Build and Deploy web app
        uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          firebase_version: "9.4.1"
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          debug: false
          message: "Deploying web app"
        if: matrix.os == 'ubuntu-latest'
