name: CI/CD for Flutter app
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.1.0
        with:
          flutter-version: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Build Android APK
        run: flutter build apk --release
        if: matrix.os == 'ubuntu-latest'
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Build iOS IPA
        uses: apple-actions/setup-ios@v1
        if: matrix.os == 'macos-latest'
      - name: Archive iOS app
        uses: apple-actions/create-xcarchive@v1
        if: matrix.os == 'macos-latest'
        with:
          scheme: Runner
          xcarchive-path: ${{ github.workspace }}/ios
      - name: Export iOS app
        uses: apple-actions/export-from-archive@v1
        if: matrix.os == 'macos-latest'
        with:
          archive-path: ${{ github.workspace }}/ios.xcarchive
          export-options: |
            {
              "method": "app-store",
              "uploadBitcode": true,
              "uploadSymbols": true
            }
          export-path: ${{ github.workspace }}
      - name: Upload to Google Play Store
        uses: r0adkll/upload-github-action@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GOOGLE_PLAY_STORE_TOKEN }}
          release_notes: release_notes.txt
          track: internal
      - name: Upload to App Store
        uses: jasonbellamy/apple-appstore-upload@v1
        if: matrix.os == 'macos-latest'
        with:
          username: ${{ secrets.APP_STORE_USERNAME }}
          password: ${{ secrets.APP_STORE_PASSWORD }}
          app_id: ${{ secrets.APP_STORE_APP_ID }}
          ipa_path: ${{ github.workspace }}/Runner.ipa
      - name: Build and Deploy web app
        uses: FirebaseExtended/firebase-actions/hosting-deploy@v0.8.0
        with:
          firebase-version: "9.4.1"
          project-id: ${{ secrets.FIREBASE_PROJECT_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          debug: false
          message: "Deploying web app"
        if: matrix.os == 'ubuntu-latest'
