name: Build and distribute

on:
  push:
    branches:
      - main

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.1

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Distribute APK
        uses: firebase/app-distribution-action@v1
        with:
          app: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          apk: build/app/outputs/flutter-apk/app-release.apk
