name: CI/CD for Flutter app
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.6.1
        with:
          flutter-version: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Build Android APK
        run: flutter build apk --release
        if: matrix.os == 'ubuntu-latest'
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Build iOS IPA
        uses: vanekjar/flutter-action-build-ios@v1
        with:
          args: --release
        if: matrix.os == 'macos-latest'
      - name: Upload to Google Play Store
        uses: r0adkll/upload-github-action@master
        if: matrix.os == 'ubuntu-latest'
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GOOGLE_PLAY_STORE_TOKEN }}
          releaseNotesFile: release_notes.txt
          track: "internal"
      - name: Upload to App Store
        uses: limao777/ios-app-store-upload@v1.3.1
        if: matrix.os == 'macos-latest'
        with:
          appId: ${{ secrets.APP_STORE_APP_ID }}
          username: ${{ secrets.APP_STORE_USERNAME }}
          password: ${{ secrets.APP_STORE_PASSWORD }}
          ipaPath: Runner.ipa
      - name: Build and Deploy web app
        uses: FirebaseExtended/flutterfire-actions@v1.9.1
        with:
          args: build web
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
        if: matrix.os == 'ubuntu-latest'
